language: cpp
sudo: required
dist: trusty
compiler: gcc
script: cd armips && ../build.sh
env:
  - BUILD_ARCH=x86
  - BUILD_ARCH=x64
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: BUILD_ARCH=x86
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-multilib
before_deploy:
  - export DEPLOY_FILE=armips-${TRAVIS_OS_NAME}-${BUILD_ARCH}-${TRAVIS_TAG}.tar.gz
  - tar -czvf $DEPLOY_FILE armips LICENSE.txt Readme.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HfmJ4PcdCA9+AlSQ5PZm0XH/+DJLt1+4j2pS8fbNigCi9eVgkxGTUK+kSQWBrHlft45yJZsbNo67M2VjUFr+iAtbhH/6e/FR223ozh53WqhPZA6jLWIAXozP38H0qYScMQCd2tnHQIoOEF8/+x2yVh4iDOpa67k58/RCRfdsrMO6USLm+cc9faBgvMkZEw+1gJsq1XN7xw3DxLFarEzSYDe7rwAkRB2n1k504et8hSwC9xYL+bmH8ZTXIIdkSCPbrymltbQjrJ8FqIHCxFlWr7M6v8sMHIMhLGFQxH07+vRPNq+eO7lnkYKqCdDV/5mGulTv/1lV6U0kSumLzW56Klcj+k1s9taHM7tw0bl3AufheQcSS0zud14KwLhaT23VLVvGP6P39GxK+y4zTQQlK45JLuWn3qYdpxwJl5vbrbDkiTEoIEIB7JJj7lTpXo8JwMKyimWr6CLDFG0yjPw6xihTH8FwLsriiqu0DF5tWHWGcBFwDETiBlQE993i6fv1QoyZls8asXZqJAjFFKdrhtGXIqvPXWnkr3yZfeTqzmFa0rXpMIohYTt9HisLBrxh/Jy7zkI217xqHMyMbjaTWH3yHaUqg0b+YcJeYxi+8Vg4lyxsXAE8IaQMKt++w3X1c2rGqKUApxgegmfZtaOjpiSZs9Aik1zsThrY/0Oux+Y=
  file: $DEPLOY_FILE
  on:
    repo: Touched/armips-binaries
    tags: true
