platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - git submodule update --init --recursive
build:
  project: armips\armips.sln
after_build:
  - ps: $env:BINARY = If (%env:CONFIGURATION=="x64") {"armips64.exe"} Else {"armips.exe"}
  - echo %BINARY%
  - copy /B armips\_Output\%BINARY% %BINARY%
  - 7z a armips-%CONFIGURATION%-%PLATFORM%.zip %BINARY%
artifacts:
  path: armips-%CONFIGURATION%-%PLATFORM%.zip
  name: Armips
