platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - git submodule update --init --recursive
build:
  project: armips\armips.sln
after_build:
  - copy /B armips\_Output\armips*.exe armips.exe
  - copy /B armips\Readme.txt Readme.txt
  - copy /B armips\LICENSE.txt LICENSE.txt
  - 7z a armips-%PLATFORM%.zip armips.exe LICENSE.txt Readme.txt
artifacts:
  path: armips-%PLATFORM%.zip
  name: Armips
deploy:
  - provider: BinTray
    username: touched
    api_key:
      secure: 0xW6/yHvT4GF0Iy2AEXWBTlFa3FJ7CzMgXJ6xy2HJQnZog3bHkNudKTiLqJZadvX
    subject: touched
    repo: armips-binaries
    package: armips
    version: v0.8
    publish: true
    override: true
    artifact: armips-%PLATFORM%.zip
