platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - git submodule update --init --recursive
build:
  project: armips\armips.sln
after_build:
  - xcopy /B armips\_Output\armips*.exe armips.exe
  - 7z a armips-%CONFIGURATION%-%PLATFORM%.zip armips.exe
artifacts:
  path: armips-%CONFIGURATION%-%PLATFORM%.zip
  name: Armips
