platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - git submodule update --init --recursive
build:
  project: armips\armips.sl
after_build:
  - 7z a armips-%CONFIGURATION%-%PLATFORM%.zip armips\_Output\armips.exe
artifacts:
  path: armips-%CONFIGURATION%-%PLATFORM%.zip
  name: Armips
